create table if not exists scans (
    id bigint generated by default as identity primary key,
    url text not null,
    classification text not null,
    confidence float8 not null,
    page_fetched boolean default false,
    timestamp timestamptz default now()
);

create table if not exists reports (
    id bigint generated by default as identity primary key,
    url text not null,
    original_classification text not null,
    user_comment text,
    timestamp timestamptz default now()
);
